# Generated by Django 3.2.5 on 2021-07-28 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa23d424-2a64-4e90-b38d-d5b413f4f508'), editable=False, primary_key=True, serialize=False),
        ),
    ]
