# Generated by Django 3.2.5 on 2021-07-28 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('072f94dd-6494-4c61-9a2f-4ffc3df22c32'), editable=False, primary_key=True, serialize=False),
        ),
    ]
